"""
09_referral_analysis.py

Phase 3 - Exploratory Data Analysis
Analyzes marketing/referral source performance:
    - Orders driven by each referral source
    - Revenue generated by each referral source
"""

from utils import load_data, save_text_report, money


def run():
    df = load_data()
    total_orders = len(df)
    total_revenue = df["TotalPrice"].sum()

    by_referral = (
        df.groupby("ReferralSource")
        .agg(
            Orders=("OrderID", "count"),
            Revenue=("TotalPrice", "sum"),
            Avg_Order_Value=("TotalPrice", "mean"),
        )
        .sort_values("Revenue", ascending=False)
    )
    by_referral["Order_Share_%"] = (by_referral["Orders"] / total_orders * 100).round(2)
    by_referral["Revenue_Share_%"] = (by_referral["Revenue"] / total_revenue * 100).round(2)

    top_source = by_referral["Revenue"].idxmax()

    lines = []
    lines.append("=" * 70)
    lines.append("REFERRAL SOURCE ANALYSIS")
    lines.append("=" * 70)
    lines.append(by_referral.round(2).to_string())
    lines.append("-" * 70)
    lines.append(f"Top-performing referral source: {top_source}")
    lines.append("=" * 70)

    report = "\n".join(lines)
    print(report)
    save_text_report("09_referral_analysis.txt", report)
    by_referral.to_csv("../outputs/09_referral_analysis.csv")


if __name__ == "__main__":
    run()
